stages:
  run_style_transfer:
    foreach:
      - The_Scream.jpg
      - Van_Gogh_Starry_Night.jpg
      - Shipwreck_of_the_Minotaur_William_Turner.jpg
      - Pablo_Picasso_Figure_dans_un_Fauteuil.jpg
      - Vassily_Kandinsky_Composition_7.jpg
    do:
      cmd: python -m src.run_style_transfer
        -p ./params.yaml
        -content ./images/Tuebingen_Neckarfront.jpg
        -style ./images/${item}
        -o ./results/generated_${item}
      deps:
        - ./src/run_style_transfer.py
        - ./src/losses.py
        - ./src/model.py
        - ./src/transforms.py
        - ./images
      outs:
        - ./results/generated_${item}
