preprocess:
  mean:
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
  resize:
    - 224
    - 224
vgg19:
  content_layers_ids:
    - 21
  style_layers_ids:
    - 0
    - 5
    - 10
    - 19
    - 28
train:
  loss:
    alpha: 1.
    beta: 10000.0
    normalize_gram_matrix: true
  iterations: 10
plots:
  title: beta=10000.
