preprocess:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  resize: [256, 256]
vgg19:
  content_layers_ids: [ 21 ]
  style_layers_ids: [ 0, 5, 10, 19, 28 ]
train:
  loss:
    alpha: 1.
    beta: 1000.
    normalize_gram_matrix: True
  iterations: 10
