data:
  content_image_name: 'dancing.jpg'
  style_image_name: 'picasso.jpg'
preprocess:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  new_size: (256, 256)
vgg19:
  content_layers: [21]
  style_layers: [0, 5, 10, 19, 28]
train:
  device: 'cuda'
  loss:
    alpha: 1.
    beta: 1000.
  iterations: 1000
